### ISSUE TITLE
Unnecessary division by 255 for rgb data

### ISSUE THREAD

**Issue by VictorZuanazzi** [hyangwinter/flownet3d_pytorch#1]
I believe it is not necessary to divide by 255 as rgb values are stored in the range [0,1]

https://github.com/hyangwinter/flownet3d_pytorch/blob/c6cd3b421643d4d2ee7cf815956de44722dda11c/data.py#L156

**Comment by hyangwinter** [comment]
Thank you for pointing this out, the code has been updated to fix this 😄
