### ISSUE TITLE
set upconvolution

### ISSUE THREAD

**Issue by zgojcic** [hyangwinter/flownet3d_pytorch#3]
Hi,

i think that your code has a bug in the set upconv layer. If you perform the knn the pos2 and pos1 should be swapped as input such that we get the nearest neighbor of each point in pos1( more points ) in pos2 (less points). 

I hope I made this clear (check line 334 of util.py)

Zan

**Comment by hyangwinter** [comment]
In the definition of KNN (line 78 of flownet3d_pytorch/lib/pointnet2_utils.py) 
```
def forward(ctx, k: int, unknown: torch.Tensor, known: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Find the k nearest neighbors of unknown in known
        :param ctx:
        :param unknown: (B, N, 3)
        :param known: (B, M, 3)
        :return:
            dist: (B, N, k) l2 distance to the three nearest neighbors
            idx: (B, N, k) index of k nearest neighbors
        """
        assert unknown.is_contiguous()
        assert known.is_contiguous()

        B, N, _ = unknown.size()
        m = known.size(1)
        dist2 = torch.cuda.FloatTensor(B, N, k)
        idx = torch.cuda.IntTensor(B, N, k)

        pointnet2.knn_wrapper(B, N, m, k, unknown, known, dist2, idx)
        return torch.sqrt(dist2), idx
```
And we find the k nearest neighbors of pos1(more) in pos2(less).

**Comment by zgojcic** [comment]
Thank you for the response it was my misunderstanding from when comparing to the original implementation.
