### ISSUE TITLE
 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by munib94** [hyangwinter/flownet3d_pytorch#6]
Hi,

I tried to train from scratch, but I get a Segmentation fault (core dumped) error. How can I fix this?

**System:**
OS: CentOS 7
Python version: 3.5
PyTorch version: 1.1.0 
Torchvision version: 0.3.0 
cudatoolkit version: 9.0
CUDA/cuDNN version: 9.0/7.4.1
GPU: Nvidia GPU GeForce GTX 1080 Ti

**Comment by munib94** [comment]
I downgraded my PyTorch and torchvision versions to 1.0.1 and 0.2.2, respectively. This did not bring up the segmentation fault when training, but it did bring up the following error:

```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from model import FlowNet3D
  File "/media/munib/pcss/flownet3d_pytorch/model.py", line 5, in <module>
    from util import PointNetSetAbstraction,PointNetFeaturePropogation,FlowEmbedding,PointNetSetUpConv
  File "/media/munib/pcss/flownet3d_pytorch/util.py", line 6, in <module>
    from lib import pointnet2_utils as pointutils
  File "/media/munib/pcss/flownet3d_pytorch/lib/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/media-server/.pyenv/versions/anaconda3-5.0.0/envs/flownet3dpy/lib/python3.5/site-packages/pointnet2-0.0.0-py3.5-linux-x86_64.egg/pointnet2_cuda.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
```

Any suggestions on how to fix this?

Update:

I upgraded to PyTorch 1.5.1 and torchvision 0.6.1 and got the same ImportError.

**Comment by hyangwinter** [comment]
Did you completely uninstall the previous pytorch and rebuild the lib when you changed the pytorch version?

Hope this answer could help you:
https://github.com/open-mmlab/mmdetection/issues/728#issuecomment-497232980

**Comment by munib94** [comment]
I used the `conda uninstall <package>` method. It's possible that the issue could be with extra cuda tools in my environment. However, I decided not to pursue this issue further as I just set up a new PC with Ubuntu and a newer graphics card. I appreciate your help.
